server:
  port: 8080

spring:
  application:
    name: excel-nth-min-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs

logging:
  level:
    com.example.excelnthminservice: INFO